/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        maven { url = uri("https://repo.spring.io/release") }
        gradlePluginPortal()
    }
}
rootProject.name = "mall-tiny"
include(":app")
include("ktorm-plus")
