/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("com.alibaba:druid-spring-boot-starter:1.2.6")
    implementation("mysql:mysql-connector-java:8.0.25")
    implementation("io.springfox:springfox-swagger2:2.9.2")
    implementation("io.springfox:springfox-swagger-ui:2.9.2")
    implementation("io.swagger:swagger-models:1.6.2")
    implementation("io.swagger:swagger-annotations:1.6.2")
    implementation("cn.hutool:hutool-all:5.7.11")
    implementation("io.jsonwebtoken:jjwt:0.9.1")
    implementation("javax.xml.bind:jaxb-api:2.3.1")

    implementation("org.ktorm:ktorm-support-mysql:3.4.1")
    implementation("org.ktorm:ktorm-jackson:3.4.1")

    compileOnly("org.postgresql:postgresql:42.2.5")

    implementation("com.baomidou:mybatis-plus-boot-starter:3.4.3.4")
    implementation("com.baomidou:mybatis-plus-generator:3.5.1")
    implementation("org.apache.velocity:velocity-engine-core:2.3")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
