/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
}

dependencies {
    implementation(project(":ktorm-plus"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    developmentOnly("org.springframework.boot:spring-boot-devtools")
     //implementation("com.alibaba:druid-spring-boot-starter:1.2.6")
    implementation("mysql:mysql-connector-java:8.0.25")
    implementation("cn.hutool:hutool-all:5.7.14")
    implementation("io.jsonwebtoken:jjwt:0.9.1")
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0")
    //implementation("com.squareup.moshi:moshi-kotlin:1.12.0")

    implementation("com.github.xiaoymin:knife4j-spring-boot-starter:3.0.3")

    implementation("org.mapstruct:mapstruct:1.5.0.Beta1")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.5.0.Beta1")

    implementation("org.ktorm:ktorm-support-mysql:3.4.1")
    implementation("org.ktorm:ktorm-jackson:3.4.1")

    implementation("org.apache.velocity:velocity-engine-core:2.3")

    testImplementation("com.github.tomakehurst:wiremock-jre8:2.31.0")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
